//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resturant_1
    {
        public int P_id { get; set; }
        public string P_name { get; set; }
        public string P_price { get; set; }
        public string P_ingredients { get; set; }
        public string P_address { get; set; }
        public string P_contact { get; set; }
        public string P_resName { get; set; }
    }
}
